import { buildClient } from "../lib/prisma";

const prisma = buildClient();

function slug(name: string) {
  return name.toLowerCase().replace(/['']/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

type SongInput = Parameters<typeof prisma.song.create>[0]["data"];
type SeedCredit = { id: string };
type SeedSong = SongInput & { producers: SeedCredit[]; engineers: SeedCredit[] };

async function upsertSongs(songs: SeedSong[], label: string, pendingCredits: Array<{ songId: string; creditId: string }>) {
  console.log(`  Creating ${label} songs...`);
  for (const { producers, engineers, ...songData } of songs) {
    const song = await prisma.song.upsert({
      where: { slug: songData.slug as string },
      update: {},
      create: songData as SongInput,
    });
    for (const p of producers) pendingCredits.push({ songId: song.id, creditId: p.id });
    for (const e of engineers) pendingCredits.push({ songId: song.id, creditId: e.id });
  }
}

async function main() {
  console.log("🌱  Seeding The Batting Average...\n");

  // ─── Labels ──────────────────────────────────────────────────────────────
  const [tde, dreamville, backwoodz, ovo, goodMusic, columbia, epic, lomaVista, tanCressida] = await Promise.all([
    prisma.label.upsert({ where: { slug: "top-dawg-entertainment" }, update: {}, create: { name: "Top Dawg Entertainment", slug: "top-dawg-entertainment" } }),
    prisma.label.upsert({ where: { slug: "dreamville-records" }, update: {}, create: { name: "Dreamville Records", slug: "dreamville-records" } }),
    prisma.label.upsert({ where: { slug: "backwoodz-studioz" }, update: {}, create: { name: "Backwoodz Studioz", slug: "backwoodz-studioz" } }),
    prisma.label.upsert({ where: { slug: "ovo-sound" }, update: {}, create: { name: "OVO Sound", slug: "ovo-sound" } }),
    prisma.label.upsert({ where: { slug: "good-music" }, update: {}, create: { name: "G.O.O.D. Music", slug: "good-music" } }),
    prisma.label.upsert({ where: { slug: "columbia-records" }, update: {}, create: { name: "Columbia Records", slug: "columbia-records" } }),
    prisma.label.upsert({ where: { slug: "epic-records" }, update: {}, create: { name: "Epic Records", slug: "epic-records" } }),
    prisma.label.upsert({ where: { slug: "loma-vista" }, update: {}, create: { name: "Loma Vista Recordings", slug: "loma-vista" } }),
    prisma.label.upsert({ where: { slug: "tan-cressida" }, update: {}, create: { name: "Tan Cressida", slug: "tan-cressida" } }),
  ]);
  console.log("✓  Labels");

  // ─── Artists ─────────────────────────────────────────────────────────────
  const [kendrick, cole, woods, drake, kanye, tyler, mac, future, travis, jid, denzel, earl] = await Promise.all([
    prisma.artist.upsert({ where: { slug: "kendrick-lamar" }, update: {}, create: { name: "Kendrick Lamar", slug: "kendrick-lamar", era: "2010s–present", artistTier: "SUPERSTAR", labelId: tde.id, bio: "Compton-born rapper widely regarded as the best of his generation. Pulitzer Prize and Grammy winner." } }),
    prisma.artist.upsert({ where: { slug: "j-cole" }, update: {}, create: { name: "J. Cole", slug: "j-cole", era: "2010s–present", artistTier: "MAINSTREAM", labelId: dreamville.id, bio: "Fayetteville-born rapper, producer, and Dreamville label founder." } }),
    prisma.artist.upsert({ where: { slug: "billy-woods" }, update: {}, create: { name: "billy woods", slug: "billy-woods", era: "2010s–present", artistTier: "UNDERGROUND", labelId: backwoodz.id, bio: "NYC underground rapper and Backwoodz Studioz founder. Dense referential lyricism over experimental production." } }),
    prisma.artist.upsert({ where: { slug: "drake" }, update: {}, create: { name: "Drake", slug: "drake", era: "2009–present", artistTier: "SUPERSTAR", labelId: ovo.id, bio: "Toronto-born rapper and singer. One of the best-selling music artists of all time." } }),
    prisma.artist.upsert({ where: { slug: "kanye-west" }, update: {}, create: { name: "Kanye West", slug: "kanye-west", era: "2004–present", artistTier: "SUPERSTAR", labelId: goodMusic.id, bio: "Chicago-born rapper and producer. One of the most influential and polarizing artists in music history." } }),
    prisma.artist.upsert({ where: { slug: "tyler-the-creator" }, update: {}, create: { name: "Tyler, the Creator", slug: "tyler-the-creator", era: "2009–present", artistTier: "MAINSTREAM", labelId: columbia.id, bio: "LA-based rapper, producer, and creative director. Meticulous self-production across wildly different sonic worlds." } }),
    prisma.artist.upsert({ where: { slug: "mac-miller" }, update: {}, create: { name: "Mac Miller", slug: "mac-miller", era: "2010–2018", artistTier: "MAINSTREAM", labelId: columbia.id, bio: "Pittsburgh-born rapper and multi-instrumentalist. Evolved from frat-rap to jazz-inflected introspection." } }),
    prisma.artist.upsert({ where: { slug: "future" }, update: {}, create: { name: "Future", slug: "future", era: "2011–present", artistTier: "MAINSTREAM", labelId: epic.id, bio: "Atlanta rapper who pioneered melodic auto-tune trap. Prolific output, consistent influence on rap's sound." } }),
    prisma.artist.upsert({ where: { slug: "travis-scott" }, update: {}, create: { name: "Travis Scott", slug: "travis-scott", era: "2013–present", artistTier: "MAINSTREAM", labelId: epic.id, bio: "Houston rapper known for psychedelic production, genre-bending albums, and record-breaking live shows." } }),
    prisma.artist.upsert({ where: { slug: "jid" }, update: {}, create: { name: "JID", slug: "jid", era: "2017–present", artistTier: "RISING", labelId: dreamville.id, bio: "Atlanta rapper with some of the most technically precise lyricism and delivery in contemporary hip-hop." } }),
    prisma.artist.upsert({ where: { slug: "denzel-curry" }, update: {}, create: { name: "Denzel Curry", slug: "denzel-curry", era: "2013–present", artistTier: "RISING", labelId: lomaVista.id, bio: "Carol City, FL rapper known for explosive energy and full-range stylistic versatility." } }),
    prisma.artist.upsert({ where: { slug: "earl-sweatshirt" }, update: {}, create: { name: "Earl Sweatshirt", slug: "earl-sweatshirt", era: "2010–present", artistTier: "INDEPENDENT", labelId: tanCressida.id, bio: "LA-based rapper with some of the most densely layered lyricism in underground hip-hop." } }),
  ]);
  console.log("✓  Artists");

  // ─── Albums ──────────────────────────────────────────────────────────────
  const [
    gkmc, tpab, fhd, kod, hidingPlaces, mapsAlbum,
    takeCare, nwts, scorpion,
    collegeDropout, mbdtf, yeezus, tlop,
    flowerBoy, igor, cmiygl,
    goodAm, divineFem, swimming, circlesAlbum,
    ds2, hndrxx,
    rodeo, birdsAlbum, astroworld, utopia,
    neverStory, diCaprio2, foreverStory,
    ta13oo, zuuAlbum, meltMyEyez,
    doris, idontlike, someRapSongs, sickAlbum,
  ] = await Promise.all([
    prisma.album.upsert({ where: { slug: "good-kid-maad-city" }, update: {}, create: { title: "good kid, m.A.A.d city", slug: "good-kid-maad-city", year: 2012, artistId: kendrick.id } }),
    prisma.album.upsert({ where: { slug: "to-pimp-a-butterfly" }, update: {}, create: { title: "To Pimp a Butterfly", slug: "to-pimp-a-butterfly", year: 2015, artistId: kendrick.id } }),
    prisma.album.upsert({ where: { slug: "2014-forest-hills-drive" }, update: {}, create: { title: "2014 Forest Hills Drive", slug: "2014-forest-hills-drive", year: 2014, artistId: cole.id } }),
    prisma.album.upsert({ where: { slug: "kod" }, update: {}, create: { title: "KOD", slug: "kod", year: 2018, artistId: cole.id } }),
    prisma.album.upsert({ where: { slug: "hiding-places" }, update: {}, create: { title: "Hiding Places", slug: "hiding-places", year: 2019, artistId: woods.id } }),
    prisma.album.upsert({ where: { slug: "maps" }, update: {}, create: { title: "Maps", slug: "maps", year: 2023, artistId: woods.id } }),
    prisma.album.upsert({ where: { slug: "take-care" }, update: {}, create: { title: "Take Care", slug: "take-care", year: 2011, artistId: drake.id } }),
    prisma.album.upsert({ where: { slug: "nothing-was-the-same" }, update: {}, create: { title: "Nothing Was the Same", slug: "nothing-was-the-same", year: 2013, artistId: drake.id } }),
    prisma.album.upsert({ where: { slug: "scorpion" }, update: {}, create: { title: "Scorpion", slug: "scorpion", year: 2018, artistId: drake.id } }),
    prisma.album.upsert({ where: { slug: "the-college-dropout" }, update: {}, create: { title: "The College Dropout", slug: "the-college-dropout", year: 2004, artistId: kanye.id } }),
    prisma.album.upsert({ where: { slug: "my-beautiful-dark-twisted-fantasy" }, update: {}, create: { title: "My Beautiful Dark Twisted Fantasy", slug: "my-beautiful-dark-twisted-fantasy", year: 2010, artistId: kanye.id } }),
    prisma.album.upsert({ where: { slug: "yeezus" }, update: {}, create: { title: "Yeezus", slug: "yeezus", year: 2013, artistId: kanye.id } }),
    prisma.album.upsert({ where: { slug: "the-life-of-pablo" }, update: {}, create: { title: "The Life of Pablo", slug: "the-life-of-pablo", year: 2016, artistId: kanye.id } }),
    prisma.album.upsert({ where: { slug: "flower-boy" }, update: {}, create: { title: "Flower Boy", slug: "flower-boy", year: 2017, artistId: tyler.id } }),
    prisma.album.upsert({ where: { slug: "igor" }, update: {}, create: { title: "IGOR", slug: "igor", year: 2019, artistId: tyler.id } }),
    prisma.album.upsert({ where: { slug: "call-me-if-you-get-lost" }, update: {}, create: { title: "Call Me If You Get Lost", slug: "call-me-if-you-get-lost", year: 2021, artistId: tyler.id } }),
    prisma.album.upsert({ where: { slug: "good-am" }, update: {}, create: { title: "GO:OD AM", slug: "good-am", year: 2015, artistId: mac.id } }),
    prisma.album.upsert({ where: { slug: "the-divine-feminine" }, update: {}, create: { title: "The Divine Feminine", slug: "the-divine-feminine", year: 2016, artistId: mac.id } }),
    prisma.album.upsert({ where: { slug: "swimming" }, update: {}, create: { title: "Swimming", slug: "swimming", year: 2018, artistId: mac.id } }),
    prisma.album.upsert({ where: { slug: "circles" }, update: {}, create: { title: "Circles", slug: "circles", year: 2020, artistId: mac.id } }),
    prisma.album.upsert({ where: { slug: "ds2" }, update: {}, create: { title: "DS2", slug: "ds2", year: 2015, artistId: future.id } }),
    prisma.album.upsert({ where: { slug: "hndrxx" }, update: {}, create: { title: "HNDRXX", slug: "hndrxx", year: 2017, artistId: future.id } }),
    prisma.album.upsert({ where: { slug: "rodeo" }, update: {}, create: { title: "Rodeo", slug: "rodeo", year: 2015, artistId: travis.id } }),
    prisma.album.upsert({ where: { slug: "birds-in-the-trap" }, update: {}, create: { title: "Birds in the Trap Sing McKnight", slug: "birds-in-the-trap", year: 2016, artistId: travis.id } }),
    prisma.album.upsert({ where: { slug: "astroworld" }, update: {}, create: { title: "ASTROWORLD", slug: "astroworld", year: 2018, artistId: travis.id } }),
    prisma.album.upsert({ where: { slug: "utopia" }, update: {}, create: { title: "UTOPIA", slug: "utopia", year: 2023, artistId: travis.id } }),
    prisma.album.upsert({ where: { slug: "the-never-story" }, update: {}, create: { title: "The Never Story", slug: "the-never-story", year: 2017, artistId: jid.id } }),
    prisma.album.upsert({ where: { slug: "dicaprio-2" }, update: {}, create: { title: "DiCaprio 2", slug: "dicaprio-2", year: 2018, artistId: jid.id } }),
    prisma.album.upsert({ where: { slug: "the-forever-story" }, update: {}, create: { title: "The Forever Story", slug: "the-forever-story", year: 2022, artistId: jid.id } }),
    prisma.album.upsert({ where: { slug: "ta13oo" }, update: {}, create: { title: "TA13OO", slug: "ta13oo", year: 2018, artistId: denzel.id } }),
    prisma.album.upsert({ where: { slug: "zuu" }, update: {}, create: { title: "ZUU", slug: "zuu", year: 2019, artistId: denzel.id } }),
    prisma.album.upsert({ where: { slug: "melt-my-eyez" }, update: {}, create: { title: "Melt My Eyez See Your Future", slug: "melt-my-eyez", year: 2022, artistId: denzel.id } }),
    prisma.album.upsert({ where: { slug: "doris" }, update: {}, create: { title: "Doris", slug: "doris", year: 2013, artistId: earl.id } }),
    prisma.album.upsert({ where: { slug: "i-dont-like-shit" }, update: {}, create: { title: "I Don't Like Shit, I Don't Go Outside", slug: "i-dont-like-shit", year: 2015, artistId: earl.id } }),
    prisma.album.upsert({ where: { slug: "some-rap-songs" }, update: {}, create: { title: "Some Rap Songs", slug: "some-rap-songs", year: 2018, artistId: earl.id } }),
    prisma.album.upsert({ where: { slug: "sick" }, update: {}, create: { title: "Sick!", slug: "sick", year: 2022, artistId: earl.id } }),
  ]);
  console.log("✓  Albums");

  // ─── Credits ─────────────────────────────────────────────────────────────
  const [
    sounwave, terrace, pharrell, dahi, thc, flyingLotus, jcoleSelf, vinylz, illmind, kennySegal,
    mixedByAli, alexTumay, kennySegalEng,
    forty, boi1da, kanyeSelf, tylerSelf, macSelf, metroBoomin, southside, wondaGurl, kennyBeats, jakeOne,
    mikeDean, jasperHarris, derekDixie,
  ] = await Promise.all([
    prisma.credit.upsert({ where: { slug: "sounwave" }, update: {}, create: { name: "Sounwave", slug: "sounwave", role: "PRODUCER" } }),
    prisma.credit.upsert({ where: { slug: "terrace-martin" }, update: {}, create: { name: "Terrace Martin", slug: "terrace-martin", role: "PRODUCER" } }),
    prisma.credit.upsert({ where: { slug: "pharrell-williams" }, update: {}, create: { name: "Pharrell Williams", slug: "pharrell-williams", role: "PRODUCER" } }),
    prisma.credit.upsert({ where: { slug: "dj-dahi" }, update: {}, create: { name: "DJ Dahi", slug: "dj-dahi", role: "PRODUCER" } }),
    prisma.credit.upsert({ where: { slug: "thc" }, update: {}, create: { name: "THC", slug: "thc", role: "PRODUCER" } }),
    prisma.credit.upsert({ where: { slug: "flying-lotus" }, update: {}, create: { name: "Flying Lotus", slug: "flying-lotus", role: "PRODUCER" } }),
    prisma.credit.upsert({ where: { slug: "j-cole-producer" }, update: {}, create: { name: "J. Cole", slug: "j-cole-producer", role: "PRODUCER" } }),
    prisma.credit.upsert({ where: { slug: "vinylz" }, update: {}, create: { name: "Vinylz", slug: "vinylz", role: "PRODUCER" } }),
    prisma.credit.upsert({ where: { slug: "illmind" }, update: {}, create: { name: "Illmind", slug: "illmind", role: "PRODUCER" } }),
    prisma.credit.upsert({ where: { slug: "kenny-segal" }, update: {}, create: { name: "Kenny Segal", slug: "kenny-segal", role: "PRODUCER" } }),
    prisma.credit.upsert({ where: { slug: "mixedbyali" }, update: {}, create: { name: "MixedByAli", slug: "mixedbyali", role: "ENGINEER" } }),
    prisma.credit.upsert({ where: { slug: "alex-tumay" }, update: {}, create: { name: "Alex Tumay", slug: "alex-tumay", role: "ENGINEER" } }),
    prisma.credit.upsert({ where: { slug: "kenny-segal-engineer" }, update: {}, create: { name: "Kenny Segal", slug: "kenny-segal-engineer", role: "ENGINEER" } }),
    prisma.credit.upsert({ where: { slug: "40-noah-shebib" }, update: {}, create: { name: "40", slug: "40-noah-shebib", role: "PRODUCER" } }),
    prisma.credit.upsert({ where: { slug: "boi-1da" }, update: {}, create: { name: "Boi-1da", slug: "boi-1da", role: "PRODUCER" } }),
    prisma.credit.upsert({ where: { slug: "kanye-west-producer" }, update: {}, create: { name: "Kanye West", slug: "kanye-west-producer", role: "PRODUCER" } }),
    prisma.credit.upsert({ where: { slug: "tyler-the-creator-producer" }, update: {}, create: { name: "Tyler, the Creator", slug: "tyler-the-creator-producer", role: "PRODUCER" } }),
    prisma.credit.upsert({ where: { slug: "mac-miller-producer" }, update: {}, create: { name: "Mac Miller", slug: "mac-miller-producer", role: "PRODUCER" } }),
    prisma.credit.upsert({ where: { slug: "metro-boomin" }, update: {}, create: { name: "Metro Boomin", slug: "metro-boomin", role: "PRODUCER" } }),
    prisma.credit.upsert({ where: { slug: "southside" }, update: {}, create: { name: "Southside", slug: "southside", role: "PRODUCER" } }),
    prisma.credit.upsert({ where: { slug: "wondagurl" }, update: {}, create: { name: "WondaGurl", slug: "wondagurl", role: "PRODUCER" } }),
    prisma.credit.upsert({ where: { slug: "kenny-beats" }, update: {}, create: { name: "Kenny Beats", slug: "kenny-beats", role: "PRODUCER" } }),
    prisma.credit.upsert({ where: { slug: "jake-one" }, update: {}, create: { name: "Jake One", slug: "jake-one", role: "PRODUCER" } }),
    prisma.credit.upsert({ where: { slug: "mike-dean" }, update: {}, create: { name: "Mike Dean", slug: "mike-dean", role: "ENGINEER" } }),
    prisma.credit.upsert({ where: { slug: "jasper-harris" }, update: {}, create: { name: "Jasper Harris", slug: "jasper-harris", role: "ENGINEER" } }),
    prisma.credit.upsert({ where: { slug: "derek-dixie" }, update: {}, create: { name: "Derek Dixie", slug: "derek-dixie", role: "ENGINEER" } }),
  ]);
  console.log("✓  Credits");

  // ─── Songs ───────────────────────────────────────────────────────────────
  const pendingCredits: Array<{ songId: string; creditId: string }> = [];

  // ── Kendrick Lamar ────────────────────────────────────────────────────────
  await upsertSongs([
    { title: "Backseat Freestyle", slug: "backseat-freestyle", year: 2012, albumId: gkmc.id, primaryArtistId: kendrick.id, lyricism_score: 88, production_score: 84, engineering_score: 86, creativity_score: 82, performance_score: 91, longevity_score: 87, sample_score: 45, critical_score: 85, cultural_moment_score: 72, peer_score: 78, lifetime_streams: 420_000_000n, peak_chart_position: 49, chart_name: "HOT_100", certification_level: "PLAT", tiktok_video_count: 300_000, virality_durability: "LASTING", sync_placement_count: 3, producers: [thc], engineers: [mixedByAli] },
    { title: "The Art of Peer Pressure", slug: "the-art-of-peer-pressure", year: 2012, albumId: gkmc.id, primaryArtistId: kendrick.id, lyricism_score: 94, production_score: 84, engineering_score: 87, creativity_score: 89, performance_score: 92, longevity_score: 91, sample_score: 40, critical_score: 91, cultural_moment_score: 75, peer_score: 82, lifetime_streams: 200_000_000n, certification_level: "GOLD", tiktok_video_count: 80_000, virality_durability: "LASTING", producers: [sounwave], engineers: [mixedByAli] },
    { title: "Money Trees", slug: "money-trees", year: 2012, albumId: gkmc.id, primaryArtistId: kendrick.id, lyricism_score: 96, production_score: 90, engineering_score: 89, creativity_score: 93, performance_score: 92, longevity_score: 96, sample_score: 70, critical_score: 95, cultural_moment_score: 88, peer_score: 93, lifetime_streams: 700_000_000n, peak_chart_position: 83, chart_name: "HOT_100", certification_level: "THREE_PLAT", tiktok_video_count: 600_000, ugc_volume: 350_000, stream_spike_post_viral: true, virality_durability: "LASTING", sync_placement_count: 6, producers: [dahi], engineers: [mixedByAli] },
    { title: "Poetic Justice", slug: "poetic-justice", year: 2012, albumId: gkmc.id, primaryArtistId: kendrick.id, lyricism_score: 90, production_score: 87, engineering_score: 87, creativity_score: 86, performance_score: 89, longevity_score: 88, sample_score: 78, critical_score: 84, cultural_moment_score: 80, peer_score: 82, lifetime_streams: 550_000_000n, peak_chart_position: 33, chart_name: "HOT_100", certification_level: "TWO_PLAT", tiktok_video_count: 400_000, virality_durability: "LASTING", producers: [dahi], engineers: [mixedByAli] },
    { title: "Sing About Me, I'm Dying of Thirst", slug: "sing-about-me-im-dying-of-thirst", year: 2012, albumId: gkmc.id, primaryArtistId: kendrick.id, lyricism_score: 99, production_score: 84, engineering_score: 88, creativity_score: 96, performance_score: 97, longevity_score: 97, sample_score: 50, critical_score: 98, cultural_moment_score: 84, peer_score: 95, lifetime_streams: 380_000_000n, certification_level: "GOLD", tiktok_video_count: 120_000, virality_durability: "LASTING", sync_placement_count: 2, producers: [thc], engineers: [mixedByAli] },
    { title: "m.A.A.d city", slug: "maad-city", year: 2012, albumId: gkmc.id, primaryArtistId: kendrick.id, lyricism_score: 97, production_score: 92, engineering_score: 90, creativity_score: 95, performance_score: 97, longevity_score: 96, sample_score: 75, critical_score: 96, cultural_moment_score: 92, peer_score: 94, lifetime_streams: 580_000_000n, peak_chart_position: 51, chart_name: "HOT_100", certification_level: "TWO_PLAT", tiktok_video_count: 450_000, ugc_volume: 250_000, virality_durability: "LASTING", sync_placement_count: 7, producers: [sounwave], engineers: [mixedByAli] },
    { title: "King Kunta", slug: "king-kunta", year: 2015, albumId: tpab.id, primaryArtistId: kendrick.id, lyricism_score: 97, production_score: 91, engineering_score: 91, creativity_score: 95, performance_score: 98, longevity_score: 97, sample_score: 70, critical_score: 98, cultural_moment_score: 93, peer_score: 96, lifetime_streams: 850_000_000n, peak_chart_position: 54, chart_name: "HOT_100", certification_level: "PLAT", tiktok_video_count: 600_000, ugc_volume: 300_000, virality_durability: "LASTING", sync_placement_count: 5, producers: [sounwave], engineers: [mixedByAli] },
    { title: "Alright", slug: "alright", year: 2015, albumId: tpab.id, primaryArtistId: kendrick.id, lyricism_score: 97, production_score: 89, engineering_score: 91, creativity_score: 96, performance_score: 96, longevity_score: 99, sample_score: 65, critical_score: 99, cultural_moment_score: 100, peer_score: 97, lifetime_streams: 700_000_000n, peak_chart_position: 68, chart_name: "HOT_100", certification_level: "TWO_PLAT", tiktok_video_count: 500_000, platform_trend_peaks: 3, ugc_volume: 400_000, stream_spike_post_viral: true, search_volume_surge: true, virality_durability: "LASTING", sync_placement_count: 5, producers: [pharrell], engineers: [mixedByAli] },
    { title: "u", slug: "u", year: 2015, albumId: tpab.id, primaryArtistId: kendrick.id, lyricism_score: 98, production_score: 84, engineering_score: 88, creativity_score: 93, performance_score: 98, longevity_score: 93, sample_score: 35, critical_score: 96, cultural_moment_score: 80, peer_score: 91, lifetime_streams: 180_000_000n, certification_level: "GOLD", tiktok_video_count: 90_000, virality_durability: "LASTING", producers: [sounwave, terrace], engineers: [mixedByAli] },
    { title: "How Much a Dollar Cost", slug: "how-much-a-dollar-cost", year: 2015, albumId: tpab.id, primaryArtistId: kendrick.id, lyricism_score: 99, production_score: 87, engineering_score: 90, creativity_score: 97, performance_score: 97, longevity_score: 98, sample_score: 55, critical_score: 99, cultural_moment_score: 88, peer_score: 96, lifetime_streams: 400_000_000n, certification_level: "PLAT", tiktok_video_count: 200_000, virality_durability: "LASTING", sync_placement_count: 3, producers: [sounwave, terrace], engineers: [mixedByAli] },
  ], "Kendrick Lamar", pendingCredits);

  // ── J. Cole ───────────────────────────────────────────────────────────────
  await upsertSongs([
    { title: "03 Adolescence", slug: "03-adolescence", year: 2014, albumId: fhd.id, primaryArtistId: cole.id, lyricism_score: 90, production_score: 82, engineering_score: 80, creativity_score: 84, performance_score: 85, longevity_score: 85, sample_score: 30, critical_score: 86, cultural_moment_score: 68, peer_score: 75, lifetime_streams: 220_000_000n, certification_level: "PLAT", tiktok_video_count: 150_000, virality_durability: "LASTING", producers: [jcoleSelf], engineers: [alexTumay] },
    { title: "Wet Dreamz", slug: "wet-dreamz", year: 2014, albumId: fhd.id, primaryArtistId: cole.id, lyricism_score: 85, production_score: 80, engineering_score: 79, creativity_score: 80, performance_score: 84, longevity_score: 79, sample_score: 25, critical_score: 78, cultural_moment_score: 65, peer_score: 68, lifetime_streams: 310_000_000n, peak_chart_position: 92, chart_name: "HOT_100", certification_level: "PLAT", tiktok_video_count: 250_000, virality_durability: "LASTING", producers: [jcoleSelf], engineers: [alexTumay] },
    { title: "No Role Modelz", slug: "no-role-modelz", year: 2014, albumId: fhd.id, primaryArtistId: cole.id, lyricism_score: 88, production_score: 84, engineering_score: 82, creativity_score: 84, performance_score: 90, longevity_score: 90, sample_score: 55, critical_score: 88, cultural_moment_score: 85, peer_score: 82, lifetime_streams: 780_000_000n, peak_chart_position: 28, chart_name: "HOT_100", certification_level: "FIVE_PLAT", tiktok_video_count: 700_000, ugc_volume: 400_000, stream_spike_post_viral: true, virality_durability: "LASTING", sync_placement_count: 8, producers: [jcoleSelf], engineers: [alexTumay] },
    { title: "Love Yourz", slug: "love-yourz", year: 2014, albumId: fhd.id, primaryArtistId: cole.id, lyricism_score: 91, production_score: 82, engineering_score: 80, creativity_score: 87, performance_score: 87, longevity_score: 91, sample_score: 35, critical_score: 90, cultural_moment_score: 82, peer_score: 83, lifetime_streams: 550_000_000n, certification_level: "PLAT", tiktok_video_count: 350_000, platform_trend_peaks: 2, virality_durability: "LASTING", sync_placement_count: 5, producers: [jcoleSelf], engineers: [alexTumay] },
    { title: "Apparently", slug: "apparently", year: 2014, albumId: fhd.id, primaryArtistId: cole.id, lyricism_score: 89, production_score: 83, engineering_score: 81, creativity_score: 86, performance_score: 86, longevity_score: 83, sample_score: 30, critical_score: 85, cultural_moment_score: 72, peer_score: 77, lifetime_streams: 200_000_000n, certification_level: "GOLD", tiktok_video_count: 100_000, virality_durability: "LASTING", producers: [jcoleSelf], engineers: [alexTumay] },
    { title: "Fire Squad", slug: "fire-squad", year: 2014, albumId: fhd.id, primaryArtistId: cole.id, lyricism_score: 86, production_score: 80, engineering_score: 78, creativity_score: 82, performance_score: 85, longevity_score: 77, sample_score: 40, critical_score: 80, cultural_moment_score: 68, peer_score: 70, lifetime_streams: 140_000_000n, certification_level: "GOLD", tiktok_video_count: 60_000, virality_durability: "LASTING", producers: [jcoleSelf], engineers: [alexTumay] },
    { title: "ATM", slug: "atm", year: 2018, albumId: kod.id, primaryArtistId: cole.id, lyricism_score: 84, production_score: 81, engineering_score: 79, creativity_score: 82, performance_score: 87, longevity_score: 77, sample_score: 28, critical_score: 78, cultural_moment_score: 70, peer_score: 70, lifetime_streams: 380_000_000n, peak_chart_position: 47, chart_name: "HOT_100", certification_level: "PLAT", tiktok_video_count: 200_000, virality_durability: "LASTING", producers: [jcoleSelf], engineers: [alexTumay] },
    { title: "FRIENDS", slug: "friends", year: 2018, albumId: kod.id, primaryArtistId: cole.id, lyricism_score: 83, production_score: 79, engineering_score: 78, creativity_score: 78, performance_score: 82, longevity_score: 73, sample_score: 22, critical_score: 75, cultural_moment_score: 65, peer_score: 65, lifetime_streams: 280_000_000n, certification_level: "GOLD", tiktok_video_count: 100_000, virality_durability: "LASTING", producers: [jcoleSelf, vinylz], engineers: [alexTumay] },
    { title: "Kevin's Heart", slug: "kevins-heart", year: 2018, albumId: kod.id, primaryArtistId: cole.id, lyricism_score: 74, production_score: 72, engineering_score: 75, creativity_score: 70, performance_score: 74, longevity_score: 55, sample_score: 20, critical_score: 60, cultural_moment_score: 42, peer_score: 48, lifetime_streams: 180_000_000n, peak_chart_position: 38, chart_name: "HOT_100", certification_level: "PLAT", tiktok_video_count: 180_000, virality_durability: "FADED", producers: [jcoleSelf], engineers: [alexTumay] },
    { title: "Once an Addict", slug: "once-an-addict", year: 2018, albumId: kod.id, primaryArtistId: cole.id, lyricism_score: 86, production_score: 79, engineering_score: 76, creativity_score: 82, performance_score: 83, longevity_score: 72, sample_score: 25, critical_score: 78, cultural_moment_score: 64, peer_score: 68, lifetime_streams: 120_000_000n, certification_level: "NONE", tiktok_video_count: 50_000, virality_durability: "LASTING", producers: [jcoleSelf], engineers: [alexTumay] },
  ], "J. Cole", pendingCredits);

  // ── billy woods ───────────────────────────────────────────────────────────
  await upsertSongs([
    { title: "Solid Gold", slug: "solid-gold", year: 2019, albumId: hidingPlaces.id, primaryArtistId: woods.id, lyricism_score: 94, production_score: 85, engineering_score: 76, creativity_score: 90, performance_score: 84, longevity_score: 83, sample_score: 20, critical_score: 88, cultural_moment_score: 55, peer_score: 78, lifetime_streams: 3_200_000n, certification_level: "NONE", tiktok_video_count: 8_000, virality_durability: "LASTING", producers: [kennySegal], engineers: [kennySegalEng] },
    { title: "Red Dust", slug: "red-dust", year: 2019, albumId: hidingPlaces.id, primaryArtistId: woods.id, lyricism_score: 93, production_score: 83, engineering_score: 74, creativity_score: 88, performance_score: 82, longevity_score: 79, sample_score: 18, critical_score: 85, cultural_moment_score: 48, peer_score: 74, lifetime_streams: 1_800_000n, certification_level: "NONE", tiktok_video_count: 4_000, virality_durability: "LASTING", producers: [kennySegal], engineers: [kennySegalEng] },
    { title: "Year Zero", slug: "year-zero", year: 2019, albumId: hidingPlaces.id, primaryArtistId: woods.id, lyricism_score: 91, production_score: 82, engineering_score: 73, creativity_score: 87, performance_score: 80, longevity_score: 76, sample_score: 15, critical_score: 83, cultural_moment_score: 44, peer_score: 70, lifetime_streams: 1_200_000n, certification_level: "NONE", tiktok_video_count: 2_000, virality_durability: "LASTING", producers: [kennySegal], engineers: [kennySegalEng] },
    { title: "Dog Whistle", slug: "dog-whistle", year: 2019, albumId: hidingPlaces.id, primaryArtistId: woods.id, lyricism_score: 90, production_score: 80, engineering_score: 72, creativity_score: 85, performance_score: 78, longevity_score: 70, sample_score: 12, critical_score: 80, cultural_moment_score: 40, peer_score: 65, lifetime_streams: 900_000n, certification_level: "NONE", tiktok_video_count: 1_500, virality_durability: "LASTING", producers: [kennySegal], engineers: [kennySegalEng] },
    { title: "Spongebob", slug: "spongebob", year: 2023, albumId: mapsAlbum.id, primaryArtistId: woods.id, lyricism_score: 96, production_score: 87, engineering_score: 78, creativity_score: 93, performance_score: 87, longevity_score: 86, sample_score: 22, critical_score: 92, cultural_moment_score: 65, peer_score: 85, lifetime_streams: 5_500_000n, certification_level: "NONE", tiktok_video_count: 15_000, virality_durability: "LASTING", sync_placement_count: 1, producers: [kennySegal], engineers: [kennySegalEng] },
    { title: "FaceTime", slug: "facetime", year: 2023, albumId: mapsAlbum.id, primaryArtistId: woods.id, lyricism_score: 95, production_score: 86, engineering_score: 77, creativity_score: 91, performance_score: 85, longevity_score: 82, sample_score: 20, critical_score: 89, cultural_moment_score: 60, peer_score: 82, lifetime_streams: 4_000_000n, certification_level: "NONE", tiktok_video_count: 10_000, virality_durability: "LASTING", producers: [kennySegal], engineers: [kennySegalEng] },
    { title: "Babylon by Bus", slug: "babylon-by-bus", year: 2023, albumId: mapsAlbum.id, primaryArtistId: woods.id, lyricism_score: 90, production_score: 84, engineering_score: 75, creativity_score: 88, performance_score: 82, longevity_score: 72, sample_score: 15, critical_score: 83, cultural_moment_score: 48, peer_score: 72, lifetime_streams: 1_900_000n, certification_level: "NONE", tiktok_video_count: 3_000, virality_durability: "LASTING", producers: [kennySegal], engineers: [kennySegalEng] },
    { title: "Maps", slug: "maps-song", year: 2023, albumId: mapsAlbum.id, primaryArtistId: woods.id, lyricism_score: 92, production_score: 85, engineering_score: 76, creativity_score: 89, performance_score: 83, longevity_score: 77, sample_score: 18, critical_score: 86, cultural_moment_score: 52, peer_score: 76, lifetime_streams: 2_600_000n, certification_level: "NONE", tiktok_video_count: 5_000, virality_durability: "LASTING", producers: [kennySegal], engineers: [kennySegalEng] },
  ], "billy woods", pendingCredits);

  // ── Drake ─────────────────────────────────────────────────────────────────
  await upsertSongs([
    { title: "Marvins Room", slug: "marvins-room", year: 2011, albumId: takeCare.id, primaryArtistId: drake.id, lyricism_score: 88, production_score: 90, engineering_score: 88, creativity_score: 88, performance_score: 90, longevity_score: 92, sample_score: 40, critical_score: 85, cultural_moment_score: 88, peer_score: 84, lifetime_streams: 650_000_000n, certification_level: "PLAT", tiktok_video_count: 200_000, virality_durability: "LASTING", sync_placement_count: 4, producers: [forty], engineers: [forty] },
    { title: "Take Care", slug: "take-care-song", year: 2011, albumId: takeCare.id, primaryArtistId: drake.id, lyricism_score: 85, production_score: 91, engineering_score: 90, creativity_score: 86, performance_score: 87, longevity_score: 91, sample_score: 92, critical_score: 86, cultural_moment_score: 88, peer_score: 80, lifetime_streams: 750_000_000n, peak_chart_position: 7, chart_name: "HOT_100", certification_level: "THREE_PLAT", tiktok_video_count: 250_000, virality_durability: "LASTING", sync_placement_count: 5, producers: [forty], engineers: [forty] },
    { title: "Hold On, We're Going Home", slug: "hold-on-were-going-home", year: 2013, albumId: nwts.id, primaryArtistId: drake.id, lyricism_score: 80, production_score: 89, engineering_score: 88, creativity_score: 85, performance_score: 86, longevity_score: 90, sample_score: 30, critical_score: 82, cultural_moment_score: 90, peer_score: 79, lifetime_streams: 700_000_000n, peak_chart_position: 4, chart_name: "HOT_100", certification_level: "PLAT", tiktok_video_count: 150_000, virality_durability: "LASTING", sync_placement_count: 8, producers: [forty], engineers: [forty] },
    { title: "Started From the Bottom", slug: "started-from-the-bottom", year: 2013, albumId: nwts.id, primaryArtistId: drake.id, lyricism_score: 75, production_score: 83, engineering_score: 85, creativity_score: 78, performance_score: 82, longevity_score: 84, sample_score: 20, critical_score: 70, cultural_moment_score: 86, peer_score: 70, lifetime_streams: 800_000_000n, peak_chart_position: 6, chart_name: "HOT_100", certification_level: "THREE_PLAT", tiktok_video_count: 300_000, virality_durability: "LASTING", sync_placement_count: 6, producers: [forty], engineers: [forty] },
    { title: "Hotline Bling", slug: "hotline-bling", year: 2015, primaryArtistId: drake.id, lyricism_score: 70, production_score: 87, engineering_score: 87, creativity_score: 82, performance_score: 82, longevity_score: 92, sample_score: 35, critical_score: 72, cultural_moment_score: 97, peer_score: 71, lifetime_streams: 1_500_000_000n, peak_chart_position: 2, chart_name: "HOT_100", certification_level: "DIAMOND", tiktok_video_count: 800_000, ugc_volume: 600_000, stream_spike_post_viral: true, search_volume_surge: true, virality_durability: "LASTING", sync_placement_count: 12, producers: [forty], engineers: [forty] },
    { title: "God's Plan", slug: "gods-plan", year: 2018, albumId: scorpion.id, primaryArtistId: drake.id, lyricism_score: 72, production_score: 85, engineering_score: 88, creativity_score: 80, performance_score: 83, longevity_score: 88, sample_score: 20, critical_score: 75, cultural_moment_score: 95, peer_score: 72, lifetime_streams: 1_800_000_000n, peak_chart_position: 1, chart_name: "HOT_100", certification_level: "DIAMOND", tiktok_video_count: 700_000, ugc_volume: 500_000, stream_spike_post_viral: true, virality_durability: "LASTING", sync_placement_count: 15, producers: [forty], engineers: [forty] },
    { title: "In My Feelings", slug: "in-my-feelings", year: 2018, albumId: scorpion.id, primaryArtistId: drake.id, lyricism_score: 72, production_score: 83, engineering_score: 87, creativity_score: 78, performance_score: 80, longevity_score: 82, sample_score: 45, critical_score: 68, cultural_moment_score: 97, peer_score: 68, lifetime_streams: 1_600_000_000n, peak_chart_position: 1, chart_name: "HOT_100", certification_level: "DIAMOND", tiktok_video_count: 2_000_000, ugc_volume: 1_500_000, stream_spike_post_viral: true, search_volume_surge: true, virality_durability: "LASTING", sync_placement_count: 10, producers: [forty, metroBoomin], engineers: [forty] },
    { title: "Non Stop", slug: "non-stop", year: 2018, albumId: scorpion.id, primaryArtistId: drake.id, lyricism_score: 78, production_score: 86, engineering_score: 87, creativity_score: 80, performance_score: 84, longevity_score: 78, sample_score: 20, critical_score: 72, cultural_moment_score: 80, peer_score: 72, lifetime_streams: 700_000_000n, peak_chart_position: 8, chart_name: "HOT_100", certification_level: "FIVE_PLAT", tiktok_video_count: 350_000, virality_durability: "LASTING", producers: [forty, boi1da], engineers: [forty] },
  ], "Drake", pendingCredits);

  // ── Kanye West ────────────────────────────────────────────────────────────
  await upsertSongs([
    { title: "Through the Wire", slug: "through-the-wire", year: 2004, albumId: collegeDropout.id, primaryArtistId: kanye.id, lyricism_score: 92, production_score: 95, engineering_score: 82, creativity_score: 97, performance_score: 94, longevity_score: 97, sample_score: 90, critical_score: 95, cultural_moment_score: 88, peer_score: 94, lifetime_streams: 400_000_000n, peak_chart_position: 30, chart_name: "HOT_100", certification_level: "PLAT", tiktok_video_count: 150_000, virality_durability: "LASTING", sync_placement_count: 5, producers: [kanyeSelf], engineers: [mikeDean] },
    { title: "Jesus Walks", slug: "jesus-walks", year: 2004, albumId: collegeDropout.id, primaryArtistId: kanye.id, lyricism_score: 97, production_score: 95, engineering_score: 83, creativity_score: 97, performance_score: 96, longevity_score: 98, sample_score: 88, critical_score: 97, cultural_moment_score: 97, peer_score: 97, lifetime_streams: 350_000_000n, peak_chart_position: 11, chart_name: "HOT_100", certification_level: "GOLD", tiktok_video_count: 180_000, virality_durability: "LASTING", sync_placement_count: 8, producers: [kanyeSelf], engineers: [mikeDean] },
    { title: "Gold Digger", slug: "gold-digger", year: 2005, primaryArtistId: kanye.id, lyricism_score: 84, production_score: 95, engineering_score: 88, creativity_score: 90, performance_score: 88, longevity_score: 97, sample_score: 95, critical_score: 90, cultural_moment_score: 97, peer_score: 88, lifetime_streams: 800_000_000n, peak_chart_position: 1, chart_name: "HOT_100", certification_level: "FIVE_PLAT", tiktok_video_count: 400_000, ugc_volume: 300_000, stream_spike_post_viral: true, virality_durability: "LASTING", sync_placement_count: 15, producers: [kanyeSelf], engineers: [mikeDean] },
    { title: "Power", slug: "power", year: 2010, albumId: mbdtf.id, primaryArtistId: kanye.id, lyricism_score: 93, production_score: 97, engineering_score: 90, creativity_score: 97, performance_score: 95, longevity_score: 97, sample_score: 90, critical_score: 96, cultural_moment_score: 97, peer_score: 96, lifetime_streams: 600_000_000n, peak_chart_position: 5, chart_name: "HOT_100", certification_level: "PLAT", tiktok_video_count: 400_000, ugc_volume: 250_000, stream_spike_post_viral: true, virality_durability: "LASTING", sync_placement_count: 20, producers: [kanyeSelf], engineers: [mikeDean] },
    { title: "Runaway", slug: "runaway", year: 2010, albumId: mbdtf.id, primaryArtistId: kanye.id, lyricism_score: 94, production_score: 99, engineering_score: 91, creativity_score: 99, performance_score: 95, longevity_score: 99, sample_score: 80, critical_score: 99, cultural_moment_score: 96, peer_score: 99, lifetime_streams: 500_000_000n, peak_chart_position: 9, chart_name: "HOT_100", certification_level: "PLAT", tiktok_video_count: 300_000, virality_durability: "LASTING", sync_placement_count: 10, producers: [kanyeSelf], engineers: [mikeDean] },
    { title: "Black Skinhead", slug: "black-skinhead", year: 2013, albumId: yeezus.id, primaryArtistId: kanye.id, lyricism_score: 88, production_score: 96, engineering_score: 90, creativity_score: 97, performance_score: 93, longevity_score: 88, sample_score: 55, critical_score: 88, cultural_moment_score: 86, peer_score: 88, lifetime_streams: 250_000_000n, peak_chart_position: 84, chart_name: "HOT_100", certification_level: "PLAT", tiktok_video_count: 200_000, virality_durability: "LASTING", producers: [kanyeSelf], engineers: [mikeDean] },
    { title: "Ultralight Beam", slug: "ultralight-beam", year: 2016, albumId: tlop.id, primaryArtistId: kanye.id, lyricism_score: 94, production_score: 98, engineering_score: 90, creativity_score: 97, performance_score: 94, longevity_score: 95, sample_score: 60, critical_score: 96, cultural_moment_score: 92, peer_score: 96, lifetime_streams: 350_000_000n, peak_chart_position: 99, chart_name: "HOT_100", certification_level: "PLAT", tiktok_video_count: 180_000, virality_durability: "LASTING", sync_placement_count: 6, producers: [kanyeSelf], engineers: [mikeDean] },
    { title: "Father Stretch My Hands Pt. 1", slug: "father-stretch-my-hands", year: 2016, albumId: tlop.id, primaryArtistId: kanye.id, lyricism_score: 86, production_score: 96, engineering_score: 88, creativity_score: 93, performance_score: 88, longevity_score: 90, sample_score: 55, critical_score: 90, cultural_moment_score: 82, peer_score: 88, lifetime_streams: 280_000_000n, certification_level: "PLAT", tiktok_video_count: 250_000, virality_durability: "LASTING", producers: [kanyeSelf], engineers: [mikeDean] },
  ], "Kanye West", pendingCredits);

  // ── Tyler, the Creator ────────────────────────────────────────────────────
  await upsertSongs([
    { title: "See You Again", slug: "see-you-again", year: 2017, albumId: flowerBoy.id, primaryArtistId: tyler.id, lyricism_score: 87, production_score: 90, engineering_score: 84, creativity_score: 90, performance_score: 86, longevity_score: 90, sample_score: 30, critical_score: 88, cultural_moment_score: 82, peer_score: 86, lifetime_streams: 350_000_000n, certification_level: "PLAT", tiktok_video_count: 250_000, virality_durability: "LASTING", sync_placement_count: 4, producers: [tylerSelf], engineers: [jasperHarris] },
    { title: "Who Dat Boy", slug: "who-dat-boy", year: 2017, albumId: flowerBoy.id, primaryArtistId: tyler.id, lyricism_score: 88, production_score: 92, engineering_score: 84, creativity_score: 90, performance_score: 91, longevity_score: 82, sample_score: 40, critical_score: 85, cultural_moment_score: 75, peer_score: 82, lifetime_streams: 200_000_000n, certification_level: "GOLD", tiktok_video_count: 150_000, virality_durability: "LASTING", producers: [tylerSelf], engineers: [jasperHarris] },
    { title: "EARFQUAKE", slug: "earfquake", year: 2019, albumId: igor.id, primaryArtistId: tyler.id, lyricism_score: 80, production_score: 93, engineering_score: 87, creativity_score: 91, performance_score: 85, longevity_score: 90, sample_score: 20, critical_score: 90, cultural_moment_score: 85, peer_score: 87, lifetime_streams: 500_000_000n, peak_chart_position: 13, chart_name: "HOT_100", certification_level: "PLAT", tiktok_video_count: 300_000, virality_durability: "LASTING", producers: [tylerSelf], engineers: [jasperHarris] },
    { title: "GONE, GONE / THANK YOU", slug: "gone-gone-thank-you", year: 2019, albumId: igor.id, primaryArtistId: tyler.id, lyricism_score: 84, production_score: 95, engineering_score: 87, creativity_score: 94, performance_score: 85, longevity_score: 87, sample_score: 30, critical_score: 92, cultural_moment_score: 80, peer_score: 88, lifetime_streams: 150_000_000n, certification_level: "GOLD", tiktok_video_count: 120_000, virality_durability: "LASTING", producers: [tylerSelf], engineers: [jasperHarris] },
    { title: "NEW MAGIC WAND", slug: "new-magic-wand", year: 2019, albumId: igor.id, primaryArtistId: tyler.id, lyricism_score: 78, production_score: 89, engineering_score: 85, creativity_score: 88, performance_score: 82, longevity_score: 75, sample_score: 20, critical_score: 80, cultural_moment_score: 65, peer_score: 76, lifetime_streams: 120_000_000n, certification_level: "NONE", tiktok_video_count: 80_000, virality_durability: "LASTING", producers: [tylerSelf], engineers: [jasperHarris] },
    { title: "LUMBERJACK", slug: "lumberjack", year: 2021, albumId: cmiygl.id, primaryArtistId: tyler.id, lyricism_score: 87, production_score: 93, engineering_score: 87, creativity_score: 91, performance_score: 90, longevity_score: 85, sample_score: 35, critical_score: 88, cultural_moment_score: 80, peer_score: 85, lifetime_streams: 280_000_000n, peak_chart_position: 5, chart_name: "HOT_100", certification_level: "PLAT", tiktok_video_count: 350_000, virality_durability: "LASTING", producers: [tylerSelf], engineers: [jasperHarris] },
    { title: "SWEET / I THOUGHT YOU WANTED TO DANCE", slug: "sweet-i-thought-you-wanted-to-dance", year: 2021, albumId: cmiygl.id, primaryArtistId: tyler.id, lyricism_score: 83, production_score: 95, engineering_score: 88, creativity_score: 94, performance_score: 85, longevity_score: 85, sample_score: 40, critical_score: 90, cultural_moment_score: 75, peer_score: 86, lifetime_streams: 180_000_000n, certification_level: "GOLD", tiktok_video_count: 120_000, virality_durability: "LASTING", producers: [tylerSelf], engineers: [jasperHarris] },
    { title: "CORSO", slug: "corso", year: 2021, albumId: cmiygl.id, primaryArtistId: tyler.id, lyricism_score: 88, production_score: 91, engineering_score: 86, creativity_score: 88, performance_score: 87, longevity_score: 83, sample_score: 30, critical_score: 86, cultural_moment_score: 72, peer_score: 83, lifetime_streams: 160_000_000n, certification_level: "GOLD", tiktok_video_count: 100_000, virality_durability: "LASTING", producers: [tylerSelf], engineers: [jasperHarris] },
  ], "Tyler, the Creator", pendingCredits);

  // ── Mac Miller ────────────────────────────────────────────────────────────
  await upsertSongs([
    { title: "Congratulations", slug: "congratulations", year: 2015, albumId: goodAm.id, primaryArtistId: mac.id, lyricism_score: 82, production_score: 86, engineering_score: 84, creativity_score: 85, performance_score: 82, longevity_score: 82, sample_score: 25, critical_score: 80, cultural_moment_score: 72, peer_score: 78, lifetime_streams: 250_000_000n, certification_level: "PLAT", tiktok_video_count: 150_000, virality_durability: "LASTING", sync_placement_count: 3, producers: [macSelf], engineers: [derekDixie] },
    { title: "Dang!", slug: "dang", year: 2016, albumId: divineFem.id, primaryArtistId: mac.id, lyricism_score: 83, production_score: 88, engineering_score: 85, creativity_score: 87, performance_score: 85, longevity_score: 88, sample_score: 30, critical_score: 85, cultural_moment_score: 78, peer_score: 83, lifetime_streams: 400_000_000n, certification_level: "PLAT", tiktok_video_count: 200_000, virality_durability: "LASTING", sync_placement_count: 5, producers: [macSelf], engineers: [derekDixie] },
    { title: "Programs", slug: "programs", year: 2016, albumId: divineFem.id, primaryArtistId: mac.id, lyricism_score: 82, production_score: 87, engineering_score: 84, creativity_score: 86, performance_score: 83, longevity_score: 83, sample_score: 25, critical_score: 83, cultural_moment_score: 72, peer_score: 80, lifetime_streams: 200_000_000n, certification_level: "GOLD", tiktok_video_count: 100_000, virality_durability: "LASTING", producers: [macSelf], engineers: [derekDixie] },
    { title: "Small Worlds", slug: "small-worlds", year: 2018, albumId: swimming.id, primaryArtistId: mac.id, lyricism_score: 89, production_score: 90, engineering_score: 87, creativity_score: 89, performance_score: 88, longevity_score: 90, sample_score: 35, critical_score: 91, cultural_moment_score: 82, peer_score: 88, lifetime_streams: 300_000_000n, certification_level: "PLAT", tiktok_video_count: 150_000, virality_durability: "LASTING", sync_placement_count: 4, producers: [macSelf], engineers: [derekDixie] },
    { title: "What's the Use?", slug: "whats-the-use", year: 2018, albumId: swimming.id, primaryArtistId: mac.id, lyricism_score: 84, production_score: 92, engineering_score: 88, creativity_score: 90, performance_score: 84, longevity_score: 86, sample_score: 30, critical_score: 89, cultural_moment_score: 75, peer_score: 85, lifetime_streams: 200_000_000n, certification_level: "GOLD", tiktok_video_count: 120_000, virality_durability: "LASTING", producers: [macSelf], engineers: [derekDixie] },
    { title: "Self Care", slug: "self-care-mac", year: 2018, albumId: swimming.id, primaryArtistId: mac.id, lyricism_score: 83, production_score: 89, engineering_score: 86, creativity_score: 87, performance_score: 83, longevity_score: 87, sample_score: 25, critical_score: 87, cultural_moment_score: 80, peer_score: 83, lifetime_streams: 350_000_000n, certification_level: "PLAT", tiktok_video_count: 180_000, virality_durability: "LASTING", sync_placement_count: 5, producers: [macSelf], engineers: [derekDixie] },
    { title: "Circles", slug: "circles-song", year: 2020, albumId: circlesAlbum.id, primaryArtistId: mac.id, lyricism_score: 87, production_score: 88, engineering_score: 86, creativity_score: 88, performance_score: 86, longevity_score: 90, sample_score: 20, critical_score: 90, cultural_moment_score: 87, peer_score: 88, lifetime_streams: 500_000_000n, certification_level: "PLAT", tiktok_video_count: 200_000, virality_durability: "LASTING", sync_placement_count: 6, producers: [macSelf], engineers: [derekDixie] },
    { title: "Good News", slug: "good-news", year: 2020, albumId: circlesAlbum.id, primaryArtistId: mac.id, lyricism_score: 86, production_score: 87, engineering_score: 85, creativity_score: 87, performance_score: 85, longevity_score: 88, sample_score: 20, critical_score: 88, cultural_moment_score: 88, peer_score: 85, lifetime_streams: 350_000_000n, certification_level: "PLAT", tiktok_video_count: 180_000, virality_durability: "LASTING", sync_placement_count: 5, producers: [macSelf], engineers: [derekDixie] },
  ], "Mac Miller", pendingCredits);

  // ── Future ────────────────────────────────────────────────────────────────
  await upsertSongs([
    { title: "Codeine Crazy", slug: "codeine-crazy", year: 2014, primaryArtistId: future.id, lyricism_score: 80, production_score: 87, engineering_score: 82, creativity_score: 84, performance_score: 87, longevity_score: 86, sample_score: 15, critical_score: 79, cultural_moment_score: 80, peer_score: 80, lifetime_streams: 250_000_000n, certification_level: "PLAT", tiktok_video_count: 200_000, virality_durability: "LASTING", producers: [metroBoomin], engineers: [mixedByAli] },
    { title: "March Madness", slug: "march-madness", year: 2015, albumId: ds2.id, primaryArtistId: future.id, lyricism_score: 76, production_score: 88, engineering_score: 84, creativity_score: 84, performance_score: 88, longevity_score: 84, sample_score: 20, critical_score: 75, cultural_moment_score: 82, peer_score: 78, lifetime_streams: 400_000_000n, certification_level: "TWO_PLAT", tiktok_video_count: 250_000, virality_durability: "LASTING", producers: [southside], engineers: [mixedByAli] },
    { title: "Stick Talk", slug: "stick-talk", year: 2015, albumId: ds2.id, primaryArtistId: future.id, lyricism_score: 68, production_score: 86, engineering_score: 82, creativity_score: 80, performance_score: 85, longevity_score: 78, sample_score: 15, critical_score: 70, cultural_moment_score: 72, peer_score: 70, lifetime_streams: 300_000_000n, certification_level: "PLAT", tiktok_video_count: 200_000, virality_durability: "LASTING", producers: [southside], engineers: [mixedByAli] },
    { title: "Low Life", slug: "low-life", year: 2016, primaryArtistId: future.id, lyricism_score: 74, production_score: 89, engineering_score: 83, creativity_score: 82, performance_score: 86, longevity_score: 84, sample_score: 25, critical_score: 76, cultural_moment_score: 80, peer_score: 76, lifetime_streams: 350_000_000n, certification_level: "TWO_PLAT", tiktok_video_count: 200_000, virality_durability: "LASTING", producers: [metroBoomin], engineers: [mixedByAli] },
    { title: "Mask Off", slug: "mask-off", year: 2017, primaryArtistId: future.id, lyricism_score: 70, production_score: 87, engineering_score: 84, creativity_score: 86, performance_score: 84, longevity_score: 90, sample_score: 92, critical_score: 80, cultural_moment_score: 96, peer_score: 80, lifetime_streams: 1_200_000_000n, peak_chart_position: 1, chart_name: "HOT_100", certification_level: "DIAMOND", tiktok_video_count: 1_500_000, ugc_volume: 1_000_000, stream_spike_post_viral: true, search_volume_surge: true, virality_durability: "LASTING", sync_placement_count: 12, producers: [metroBoomin], engineers: [mixedByAli] },
    { title: "Rent Money", slug: "rent-money", year: 2015, albumId: ds2.id, primaryArtistId: future.id, lyricism_score: 75, production_score: 86, engineering_score: 82, creativity_score: 81, performance_score: 85, longevity_score: 78, sample_score: 18, critical_score: 72, cultural_moment_score: 68, peer_score: 72, lifetime_streams: 180_000_000n, certification_level: "GOLD", tiktok_video_count: 100_000, virality_durability: "LASTING", producers: [southside, metroBoomin], engineers: [mixedByAli] },
    { title: "Use Me", slug: "use-me", year: 2017, albumId: hndrxx.id, primaryArtistId: future.id, lyricism_score: 74, production_score: 87, engineering_score: 85, creativity_score: 83, performance_score: 85, longevity_score: 78, sample_score: 20, critical_score: 72, cultural_moment_score: 72, peer_score: 74, lifetime_streams: 200_000_000n, certification_level: "PLAT", tiktok_video_count: 100_000, virality_durability: "LASTING", producers: [metroBoomin], engineers: [mixedByAli] },
    { title: "Turn On the Lights", slug: "turn-on-the-lights", year: 2012, primaryArtistId: future.id, lyricism_score: 68, production_score: 82, engineering_score: 78, creativity_score: 78, performance_score: 80, longevity_score: 78, sample_score: 20, critical_score: 70, cultural_moment_score: 75, peer_score: 68, lifetime_streams: 200_000_000n, peak_chart_position: 75, chart_name: "HOT_100", certification_level: "PLAT", tiktok_video_count: 80_000, virality_durability: "LASTING", producers: [metroBoomin], engineers: [mixedByAli] },
  ], "Future", pendingCredits);

  // ── Travis Scott ──────────────────────────────────────────────────────────
  await upsertSongs([
    { title: "Antidote", slug: "antidote", year: 2015, albumId: rodeo.id, primaryArtistId: travis.id, lyricism_score: 72, production_score: 88, engineering_score: 86, creativity_score: 86, performance_score: 87, longevity_score: 86, sample_score: 20, critical_score: 78, cultural_moment_score: 83, peer_score: 78, lifetime_streams: 600_000_000n, certification_level: "THREE_PLAT", tiktok_video_count: 300_000, virality_durability: "LASTING", sync_placement_count: 6, producers: [wondaGurl], engineers: [mikeDean] },
    { title: "goosebumps", slug: "goosebumps", year: 2016, albumId: birdsAlbum.id, primaryArtistId: travis.id, lyricism_score: 74, production_score: 91, engineering_score: 87, creativity_score: 88, performance_score: 88, longevity_score: 88, sample_score: 25, critical_score: 80, cultural_moment_score: 85, peer_score: 80, lifetime_streams: 800_000_000n, peak_chart_position: 13, chart_name: "HOT_100", certification_level: "FIVE_PLAT", tiktok_video_count: 400_000, virality_durability: "LASTING", sync_placement_count: 8, producers: [wondaGurl], engineers: [mikeDean] },
    { title: "Butterfly Effect", slug: "butterfly-effect", year: 2017, primaryArtistId: travis.id, lyricism_score: 72, production_score: 88, engineering_score: 86, creativity_score: 86, performance_score: 85, longevity_score: 82, sample_score: 20, critical_score: 75, cultural_moment_score: 80, peer_score: 75, lifetime_streams: 500_000_000n, certification_level: "THREE_PLAT", tiktok_video_count: 250_000, virality_durability: "LASTING", producers: [wondaGurl], engineers: [mikeDean] },
    { title: "STARGAZING", slug: "stargazing", year: 2018, albumId: astroworld.id, primaryArtistId: travis.id, lyricism_score: 74, production_score: 93, engineering_score: 88, creativity_score: 90, performance_score: 84, longevity_score: 86, sample_score: 25, critical_score: 84, cultural_moment_score: 80, peer_score: 80, lifetime_streams: 500_000_000n, certification_level: "PLAT", tiktok_video_count: 250_000, virality_durability: "LASTING", producers: [wondaGurl], engineers: [mikeDean] },
    { title: "SICKO MODE", slug: "sicko-mode", year: 2018, albumId: astroworld.id, primaryArtistId: travis.id, lyricism_score: 80, production_score: 96, engineering_score: 90, creativity_score: 94, performance_score: 88, longevity_score: 94, sample_score: 30, critical_score: 90, cultural_moment_score: 97, peer_score: 88, lifetime_streams: 2_000_000_000n, peak_chart_position: 1, chart_name: "HOT_100", certification_level: "DIAMOND", tiktok_video_count: 1_000_000, ugc_volume: 700_000, stream_spike_post_viral: true, search_volume_surge: true, virality_durability: "LASTING", sync_placement_count: 20, producers: [wondaGurl, boi1da], engineers: [mikeDean] },
    { title: "Highest in the Room", slug: "highest-in-the-room", year: 2019, primaryArtistId: travis.id, lyricism_score: 68, production_score: 88, engineering_score: 87, creativity_score: 83, performance_score: 82, longevity_score: 78, sample_score: 15, critical_score: 70, cultural_moment_score: 80, peer_score: 70, lifetime_streams: 600_000_000n, peak_chart_position: 1, chart_name: "HOT_100", certification_level: "THREE_PLAT", tiktok_video_count: 300_000, virality_durability: "LASTING", producers: [wondaGurl], engineers: [mikeDean] },
    { title: "WAKE UP", slug: "wake-up-travis", year: 2023, albumId: utopia.id, primaryArtistId: travis.id, lyricism_score: 72, production_score: 93, engineering_score: 88, creativity_score: 88, performance_score: 80, longevity_score: 78, sample_score: 30, critical_score: 76, cultural_moment_score: 72, peer_score: 76, lifetime_streams: 200_000_000n, certification_level: "NONE", tiktok_video_count: 150_000, virality_durability: "LASTING", producers: [wondaGurl], engineers: [mikeDean] },
    { title: "FE!N", slug: "fein", year: 2023, albumId: utopia.id, primaryArtistId: travis.id, lyricism_score: 70, production_score: 92, engineering_score: 88, creativity_score: 87, performance_score: 82, longevity_score: 80, sample_score: 20, critical_score: 74, cultural_moment_score: 80, peer_score: 74, lifetime_streams: 400_000_000n, peak_chart_position: 4, chart_name: "HOT_100", certification_level: "PLAT", tiktok_video_count: 400_000, ugc_volume: 300_000, stream_spike_post_viral: true, virality_durability: "LASTING", producers: [wondaGurl, metroBoomin], engineers: [mikeDean] },
  ], "Travis Scott", pendingCredits);

  // ── JID ───────────────────────────────────────────────────────────────────
  await upsertSongs([
    { title: "Workin Out", slug: "workin-out", year: 2017, albumId: neverStory.id, primaryArtistId: jid.id, lyricism_score: 86, production_score: 79, engineering_score: 76, creativity_score: 82, performance_score: 86, longevity_score: 72, sample_score: 15, critical_score: 76, cultural_moment_score: 52, peer_score: 70, lifetime_streams: 15_000_000n, certification_level: "NONE", tiktok_video_count: 20_000, virality_durability: "LASTING", producers: [kennySegal], engineers: [mixedByAli] },
    { title: "151 Rum", slug: "151-rum", year: 2018, albumId: diCaprio2.id, primaryArtistId: jid.id, lyricism_score: 92, production_score: 84, engineering_score: 80, creativity_score: 88, performance_score: 92, longevity_score: 82, sample_score: 20, critical_score: 84, cultural_moment_score: 65, peer_score: 80, lifetime_streams: 40_000_000n, certification_level: "NONE", tiktok_video_count: 30_000, virality_durability: "LASTING", producers: [kennySegal], engineers: [mixedByAli] },
    { title: "NEVER", slug: "never-jid", year: 2018, albumId: diCaprio2.id, primaryArtistId: jid.id, lyricism_score: 93, production_score: 82, engineering_score: 79, creativity_score: 86, performance_score: 91, longevity_score: 82, sample_score: 18, critical_score: 83, cultural_moment_score: 60, peer_score: 79, lifetime_streams: 25_000_000n, certification_level: "NONE", tiktok_video_count: 20_000, virality_durability: "LASTING", producers: [kennySegal], engineers: [mixedByAli] },
    { title: "Hereditary", slug: "hereditary", year: 2018, albumId: diCaprio2.id, primaryArtistId: jid.id, lyricism_score: 91, production_score: 83, engineering_score: 80, creativity_score: 85, performance_score: 90, longevity_score: 80, sample_score: 20, critical_score: 82, cultural_moment_score: 62, peer_score: 78, lifetime_streams: 30_000_000n, certification_level: "NONE", tiktok_video_count: 25_000, virality_durability: "LASTING", producers: [kennySegal], engineers: [mixedByAli] },
    { title: "Dance Now", slug: "dance-now", year: 2022, albumId: foreverStory.id, primaryArtistId: jid.id, lyricism_score: 94, production_score: 87, engineering_score: 83, creativity_score: 90, performance_score: 93, longevity_score: 85, sample_score: 25, critical_score: 88, cultural_moment_score: 72, peer_score: 85, lifetime_streams: 55_000_000n, certification_level: "NONE", tiktok_video_count: 50_000, virality_durability: "LASTING", producers: [kennySegal], engineers: [mixedByAli] },
    { title: "Kody Blu 31", slug: "kody-blu-31", year: 2022, albumId: foreverStory.id, primaryArtistId: jid.id, lyricism_score: 91, production_score: 86, engineering_score: 82, creativity_score: 87, performance_score: 89, longevity_score: 82, sample_score: 22, critical_score: 86, cultural_moment_score: 68, peer_score: 82, lifetime_streams: 30_000_000n, certification_level: "NONE", tiktok_video_count: 30_000, virality_durability: "LASTING", producers: [kennySegal], engineers: [mixedByAli] },
    { title: "Can't Punk Me", slug: "cant-punk-me", year: 2022, albumId: foreverStory.id, primaryArtistId: jid.id, lyricism_score: 90, production_score: 84, engineering_score: 80, creativity_score: 85, performance_score: 88, longevity_score: 78, sample_score: 18, critical_score: 83, cultural_moment_score: 62, peer_score: 79, lifetime_streams: 25_000_000n, certification_level: "NONE", tiktok_video_count: 20_000, virality_durability: "LASTING", producers: [kennySegal], engineers: [mixedByAli] },
    { title: "Off Da Zoinkys", slug: "off-da-zoinkys", year: 2018, albumId: diCaprio2.id, primaryArtistId: jid.id, lyricism_score: 88, production_score: 85, engineering_score: 78, creativity_score: 84, performance_score: 88, longevity_score: 77, sample_score: 18, critical_score: 80, cultural_moment_score: 58, peer_score: 76, lifetime_streams: 20_000_000n, certification_level: "NONE", tiktok_video_count: 15_000, virality_durability: "LASTING", producers: [kennySegal], engineers: [mixedByAli] },
  ], "JID", pendingCredits);

  // ── Denzel Curry ──────────────────────────────────────────────────────────
  await upsertSongs([
    { title: "RICKY", slug: "ricky", year: 2018, albumId: ta13oo.id, primaryArtistId: denzel.id, lyricism_score: 90, production_score: 88, engineering_score: 81, creativity_score: 87, performance_score: 90, longevity_score: 82, sample_score: 18, critical_score: 85, cultural_moment_score: 70, peer_score: 82, lifetime_streams: 30_000_000n, certification_level: "NONE", tiktok_video_count: 30_000, virality_durability: "LASTING", producers: [kennyBeats], engineers: [mixedByAli] },
    { title: "Clout Cobain", slug: "clout-cobain", year: 2019, albumId: zuuAlbum.id, primaryArtistId: denzel.id, lyricism_score: 88, production_score: 87, engineering_score: 81, creativity_score: 88, performance_score: 91, longevity_score: 80, sample_score: 15, critical_score: 83, cultural_moment_score: 72, peer_score: 80, lifetime_streams: 35_000_000n, certification_level: "NONE", tiktok_video_count: 40_000, virality_durability: "LASTING", producers: [kennyBeats], engineers: [mixedByAli] },
    { title: "UNLOCKED", slug: "unlocked-denzel", year: 2020, primaryArtistId: denzel.id, lyricism_score: 89, production_score: 88, engineering_score: 82, creativity_score: 88, performance_score: 88, longevity_score: 82, sample_score: 15, critical_score: 87, cultural_moment_score: 68, peer_score: 82, lifetime_streams: 30_000_000n, certification_level: "NONE", tiktok_video_count: 25_000, virality_durability: "LASTING", producers: [kennyBeats], engineers: [mixedByAli] },
    { title: "Walkin", slug: "walkin", year: 2022, albumId: meltMyEyez.id, primaryArtistId: denzel.id, lyricism_score: 92, production_score: 91, engineering_score: 82, creativity_score: 90, performance_score: 93, longevity_score: 85, sample_score: 20, critical_score: 88, cultural_moment_score: 76, peer_score: 85, lifetime_streams: 40_000_000n, certification_level: "NONE", tiktok_video_count: 50_000, virality_durability: "LASTING", sync_placement_count: 2, producers: [kennyBeats], engineers: [mixedByAli] },
    { title: "SPEEDBOAT", slug: "speedboat", year: 2022, albumId: meltMyEyez.id, primaryArtistId: denzel.id, lyricism_score: 90, production_score: 89, engineering_score: 82, creativity_score: 88, performance_score: 91, longevity_score: 80, sample_score: 20, critical_score: 85, cultural_moment_score: 68, peer_score: 82, lifetime_streams: 25_000_000n, certification_level: "NONE", tiktok_video_count: 30_000, virality_durability: "LASTING", producers: [kennyBeats], engineers: [mixedByAli] },
    { title: "Melt Session #1", slug: "melt-session-1", year: 2022, albumId: meltMyEyez.id, primaryArtistId: denzel.id, lyricism_score: 88, production_score: 90, engineering_score: 82, creativity_score: 89, performance_score: 87, longevity_score: 78, sample_score: 18, critical_score: 86, cultural_moment_score: 64, peer_score: 82, lifetime_streams: 15_000_000n, certification_level: "NONE", tiktok_video_count: 15_000, virality_durability: "LASTING", producers: [kennyBeats], engineers: [mixedByAli] },
    { title: "The Ills", slug: "the-ills", year: 2022, albumId: meltMyEyez.id, primaryArtistId: denzel.id, lyricism_score: 85, production_score: 87, engineering_score: 80, creativity_score: 86, performance_score: 85, longevity_score: 72, sample_score: 15, critical_score: 82, cultural_moment_score: 58, peer_score: 78, lifetime_streams: 10_000_000n, certification_level: "NONE", tiktok_video_count: 8_000, virality_durability: "LASTING", producers: [kennyBeats], engineers: [mixedByAli] },
    { title: "Zatoichi", slug: "zatoichi", year: 2022, albumId: meltMyEyez.id, primaryArtistId: denzel.id, lyricism_score: 87, production_score: 88, engineering_score: 81, creativity_score: 87, performance_score: 88, longevity_score: 75, sample_score: 16, critical_score: 83, cultural_moment_score: 60, peer_score: 80, lifetime_streams: 12_000_000n, certification_level: "NONE", tiktok_video_count: 10_000, virality_durability: "LASTING", producers: [kennyBeats], engineers: [mixedByAli] },
  ], "Denzel Curry", pendingCredits);

  // ── Earl Sweatshirt ───────────────────────────────────────────────────────
  await upsertSongs([
    { title: "Chum", slug: "chum", year: 2013, albumId: doris.id, primaryArtistId: earl.id, lyricism_score: 96, production_score: 87, engineering_score: 80, creativity_score: 93, performance_score: 94, longevity_score: 93, sample_score: 50, critical_score: 95, cultural_moment_score: 82, peer_score: 92, lifetime_streams: 35_000_000n, certification_level: "NONE", tiktok_video_count: 30_000, virality_durability: "LASTING", sync_placement_count: 3, producers: [jakeOne], engineers: [mixedByAli] },
    { title: "Grief", slug: "grief", year: 2015, albumId: idontlike.id, primaryArtistId: earl.id, lyricism_score: 92, production_score: 86, engineering_score: 79, creativity_score: 90, performance_score: 88, longevity_score: 85, sample_score: 22, critical_score: 88, cultural_moment_score: 68, peer_score: 84, lifetime_streams: 12_000_000n, certification_level: "NONE", tiktok_video_count: 8_000, virality_durability: "LASTING", producers: [jakeOne], engineers: [mixedByAli] },
    { title: "I Don't Like Shit", slug: "i-dont-like-shit", year: 2015, albumId: idontlike.id, primaryArtistId: earl.id, lyricism_score: 93, production_score: 84, engineering_score: 78, creativity_score: 89, performance_score: 89, longevity_score: 82, sample_score: 20, critical_score: 87, cultural_moment_score: 65, peer_score: 84, lifetime_streams: 10_000_000n, certification_level: "NONE", tiktok_video_count: 7_000, virality_durability: "LASTING", producers: [jakeOne], engineers: [mixedByAli] },
    { title: "Nowhere2go", slug: "nowhere2go", year: 2018, albumId: someRapSongs.id, primaryArtistId: earl.id, lyricism_score: 91, production_score: 83, engineering_score: 76, creativity_score: 90, performance_score: 87, longevity_score: 82, sample_score: 30, critical_score: 88, cultural_moment_score: 65, peer_score: 82, lifetime_streams: 8_000_000n, certification_level: "NONE", tiktok_video_count: 6_000, virality_durability: "LASTING", producers: [kennySegal], engineers: [mixedByAli] },
    { title: "Tabula Rasa", slug: "tabula-rasa", year: 2018, albumId: someRapSongs.id, primaryArtistId: earl.id, lyricism_score: 90, production_score: 82, engineering_score: 75, creativity_score: 88, performance_score: 86, longevity_score: 80, sample_score: 28, critical_score: 86, cultural_moment_score: 60, peer_score: 80, lifetime_streams: 5_000_000n, certification_level: "NONE", tiktok_video_count: 4_000, virality_durability: "LASTING", producers: [kennySegal], engineers: [mixedByAli] },
    { title: "December 24", slug: "december-24", year: 2022, albumId: sickAlbum.id, primaryArtistId: earl.id, lyricism_score: 93, production_score: 84, engineering_score: 78, creativity_score: 90, performance_score: 88, longevity_score: 80, sample_score: 20, critical_score: 89, cultural_moment_score: 65, peer_score: 82, lifetime_streams: 8_000_000n, certification_level: "NONE", tiktok_video_count: 7_000, virality_durability: "LASTING", producers: [kennyBeats], engineers: [mixedByAli] },
    { title: "2010", slug: "2010-earl", year: 2022, albumId: sickAlbum.id, primaryArtistId: earl.id, lyricism_score: 92, production_score: 83, engineering_score: 78, creativity_score: 89, performance_score: 87, longevity_score: 79, sample_score: 22, critical_score: 88, cultural_moment_score: 62, peer_score: 80, lifetime_streams: 6_000_000n, certification_level: "NONE", tiktok_video_count: 5_000, virality_durability: "LASTING", producers: [kennyBeats], engineers: [mixedByAli] },
    { title: "Riot!", slug: "riot", year: 2013, albumId: doris.id, primaryArtistId: earl.id, lyricism_score: 90, production_score: 84, engineering_score: 79, creativity_score: 87, performance_score: 88, longevity_score: 78, sample_score: 35, critical_score: 85, cultural_moment_score: 65, peer_score: 82, lifetime_streams: 20_000_000n, certification_level: "NONE", tiktok_video_count: 10_000, virality_durability: "LASTING", producers: [jakeOne], engineers: [mixedByAli] },
  ], "Earl Sweatshirt", pendingCredits);

  console.log("✓  Songs");

  // ─── SongCredits ─────────────────────────────────────────────────────────
  for (const sc of pendingCredits) {
    await prisma.songCredit.upsert({
      where: { songId_creditId: sc },
      update: {},
      create: sc,
    });
  }
  console.log("✓  SongCredits\n");

  // ─── Summary ──────────────────────────────────────────────────────────────
  const tiers = await prisma.song.groupBy({ by: ["tier"], _count: true });
  const tierOrder = ["CLASSIC", "GREAT", "GOOD", "MID", "SKIP"];
  console.log("📊  Tier distribution:");
  for (const t of tierOrder) {
    const count = tiers.find((r) => r.tier === t)?._count ?? 0;
    console.log(`   ${t.padEnd(8)} ${"█".repeat(count)} (${count})`);
  }

  const topArtists = await prisma.song.groupBy({ by: ["primaryArtistId"], _avg: { batting_avg: true }, orderBy: { _avg: { batting_avg: "desc" } } });
  const nameMap = Object.fromEntries((await prisma.artist.findMany({ select: { id: true, name: true } })).map((a) => [a.id, a.name]));
  console.log("\n🎤  Artist batting averages:");
  for (const row of topArtists) {
    const avg = row._avg.batting_avg ?? 0;
    console.log(`   ${nameMap[row.primaryArtistId].padEnd(22)} .${(avg * 1000).toFixed(0).padStart(3, "0")}`);
  }

  console.log("\n🎉  Seed complete.");
}

main().catch((e) => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
